// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olmfshnswumcehnpclgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sbWZzaG5zd3VtY2VobnBjbGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODQwNDgsImV4cCI6MjA3Nzc2MDA0OH0.p2tePBkUKQP5tFgeJUjlpxJ9XtLlnuJCbz-a405brws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});